roles: move dbus_role_template out of the condition block for sysadm/…
SELinuxProject/refpolicy pull request #374
Opened 2021-05-12 05:48 UTC by yizhao1

…staff/unprivuser

After commit cc8374fd24129a2a20669bda2b57d8b029945047 (various: systemd
user fixes and additional support), the dbus_role_template is required
for all roles. But for sysadm/staff/unprivuser, this piece of code is
not included if the DISTRO is set to redhat. Move it out of the
'ifndef distro_redhat' condition block, otherwise the label of the
instance is not correct.

Before the patch if set DISTRO=redhat:
root@qemux86-64:~# ps xZ | grep "systemd --user"
root:sysadm_r:sysadm_t  240 ? Ss 0:00 /lib/systemd/systemd --user

After the patch:
root@qemux86-64:~# ps xZ | grep "systemd --user"
root:sysadm_r:sysadm_systemd_t  218 ? Ss 0:00 /lib/systemd/systemd --user

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>

2021-05-12 17:36 UTC, pebenito requested changes
It seems like the better choice would be to move the systemd block in userdom_common_user_template() into the optional with all of the other dbus calls.

2021-05-13 13:44 UTC, pebenito requested changes
Specifically, I think what needs to be done in `userdom_admin_user_template()` is:

1. replace the `dbus_system_bus_client()` with `dbus_role_template()`
2. move the `systemd_role_template()` optional block nested into the dbus optional block, similar to `accountsd_dbus_chat()`, `bluetooth_dbus_chat()`, etc. optional blocks. This reinforces that the `systemd_role_template()` needs dbus.

2021-05-13 13:44 UTC, pebenito commented on policy/modules/roles/auditadm.te
> -	dbus_role_template(auditadm, auditadm_r, auditadm_t)
This and the below ones shouldn't be removed. The only templates that call `userdom_common_user_template()` is `userdom_unpriv_user_template()` and `userdom_admin_user_template()'.

2021-05-13 13:51 UTC, pebenito commented on policy/modules/roles/auditadm.te
> -	dbus_role_template(auditadm, auditadm_r, auditadm_t)
My mistake, auditadm and secadm call the unpriv user template, but the others don't. Please check with sediff to make sure no rules are lost.

2021-05-17 08:06 UTC, yizhao1 commented
> Specifically, I think what needs to be done in `userdom_admin_user_template()` is:
> 
>     1. replace the `dbus_system_bus_client()` with `dbus_role_template()`
> 
I'm not sure if dbus_role_template() can replace dbus_system_bus_client().

In userdom_restricted_xwindows_user_template(), both of these 2 lines exists:

1097     optional_policy(`
1098         dbus_role_template($1, $1_r, $1_t)
1099         dbus_system_bus_client($1_t)


//Yi
>     2. move the `systemd_role_template()` optional block nested into the dbus optional block, similar to `accountsd_dbus_chat()`, `bluetooth_dbus_chat()`, etc. optional blocks. This reinforces that the `systemd_role_template()` needs dbus.

2021-05-18 19:24 UTC, pebenito commented
You are correct about `dbus_system_bus_client()` not being in `dbus_role_template()`, but I think it should be like this:
```
optional_policy(`
	dbus_role_template($1, $1_r, $1_t)
	dbus_system_bus_client($1_t)

	optional_policy(`
		accountsd_dbus_chat($1_t)
	')
	...
	optional_policy(`
		systemd_role_template($1, $1_r, $1_t)
	')
')
```

2021-05-19 12:33 UTC, pebenito approved these changes

2021-05-19 12:47 UTC, merged