chronyd.te: Grant chronyd_t access to the net_admin capability
SELinuxProject/refpolicy pull request #404
Opened 2021-08-31 17:05 UTC by jpds

This is required for its `hwtimestamp` option, which otherwise returns:

    ioctl(SIOCSHWTSTAMP) failed : Operation not permitted

2021-09-08 14:50 UTC, pebenito requested changes
Please add a comment in the file for why this is needed.

2021-09-13 15:53 UTC, pebenito commented
Also, is this this required for chronyd in all cases?

2021-09-13 21:14 UTC, jpds commented
@pebenito Added a comment, and this is only needed when the `hwtimestamp` option is added to the chronyd configuration.

2021-09-13 21:34 UTC, pebenito requested changes
In that case, please move the net_admin into a tunable called `chronyd_hwtimestamp`.

2021-09-14 13:30 UTC, pebenito approved these changes

2021-09-14 13:37 UTC, merged