Hookup attribute for user applications to run other applications
SELinuxProject/refpolicy pull request #412
Opened 2021-10-08 20:51 UTC by 0xC0ncord

This is the second part of the effort previously started in #381.

This PR modifies the calls to every `_role()` and `_role_template()` to use the new `$1_application_exec_domain` where appropriate, while still standardizing these role calls to use this format: `myapp_role[_template](user, user_t, user_application_exec_domain, user_r)`. This PR does not touch any role interfaces that do not have any callers.

`$1_application_exec_domain` only gets permissions needed to execute and transition to other applications, as well as using `stream_connect()` on them if it was previously given to userdomains. `$1_application_exec_domain` does not get access to read or modify application data explicitly.

Additionally, `$1_systemd_t` gets the permissions needed to monitor applications started by users in order to capture output to `journald`, check their state, and so on.

Lastly, `sudo`, `su`, and `shutdown` get a new tunable (default off) to control whether `$1_application_exec_domain` should have access to execute these administrative applications.

Fixes #365

2021-10-13 14:18 UTC, pebenito requested changes

2021-10-13 14:18 UTC, pebenito commented on policy/modules/admin/shutdown.if
> +## <param name="role_prefix">
Changing the interface to use a prefix turns it into a template.

2021-10-13 14:18 UTC, pebenito commented on policy/modules/apps/mono.if
> +		xserver_role($1, $1_mono_t, $1_application_exec_domain, $1_r)
This needs the same changes you  made elsewhere, instead of using `$1_application_exec_domain` directly.

2021-10-13 14:18 UTC, pebenito commented on policy/modules/apps/pulseaudio.if
> -	typeattribute $1 pulseaudio_client;
Why is this change needed?

2021-10-13 14:18 UTC, pebenito commented on policy/modules/apps/wine.if
> +		xserver_role($1, $1_wine_t, $1_application_exec_domain, $1_r)
Same as above.

2021-11-12 14:14 UTC, pebenito commented
From the source diff it seems ok, but I noticed something concerning from sediff:
```
$ sediff policy.33{.orig,} | grep xguest | wc -l
175
```
These are all additions.

2021-11-12 15:46 UTC, 0xC0ncord commented
> From the source diff it seems ok, but I noticed something concerning from sediff:
> 
> ```
> $ sediff policy.33{.orig,} | grep xguest | wc -l
> 175
> ```
> 
> These are all additions.

It seems that most of these new rules are to `xguest_wm_t`, and most of those are allowing `xguest_wm_t` to transition to various httpd user scripts. Everything else looks fine to me.

I'm not sure what the use case is for xguest having the ability to run httpd user scripts. If you think we should lock this down, I can add a template for httpd user script guest access, or we can remove this call altogether: https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/roles/xguest.te#L89

2021-11-12 18:58 UTC, pebenito commented
Lets remove the access. I don't see a need for a guest to have this access. If there is a good reason, we can reconsider.

2021-11-12 19:58 UTC, 0xC0ncord commented
OK. I added another commit to remove `apache` access from xguest. I also went ahead and did the same thing for normal guest for the same reason.

2021-11-14 23:57 UTC, pebenito approved these changes

2021-11-14 23:57 UTC, merged