Add type for systemd runtime units and add dbus-broker support
SELinuxProject/refpolicy pull request #479
Opened 2022-03-14 19:59 UTC by 0xC0ncord

Add a separate type for systemd runtime units and add tunables to control access to using dbus-broker as the systemd dbus daemon.

The `dbus_broker_system_bus` tunable adds the rules necessary to allow dbus-broker to be used as the system dbus daemon, and `dbus_broker_run_runtime_units` controls whether dbus-broker is allowed to run systemd runtime units. The latter tunable was added to address dbus-broker's default behavior of creating and running arbitrary units itself (instead of asking systemd) if the requested service doesn't exist.

2022-03-15 14:52 UTC, pebenito requested changes
I don't think the tunables are needed. We should also be careful about naming the type, since this is adding transient units but naming the type "runtime". Runtime implies the units that go in `/run/systemd/system`.

2022-03-15 17:39 UTC, 0xC0ncord commented
> I don't think the tunables are needed. We should also be careful about naming the type, since this is adding transient units but naming the type "runtime". Runtime implies the units that go in `/run/systemd/system`.

I added the `dbus_broker_run_runtime_units` tunable to address [this comment](https://github.com/SELinuxProject/refpolicy/issues/329#issuecomment-755418651) with regards to potentially allowing dbus-broker to transition to `initrc_t` in some circumstances. Truthfully I'm not sure how much of a problem this would be if we simply allowed the access.

As for the type naming, good point. Do you think `init_transient_unit_t` would suffice?

2022-03-18 13:32 UTC, pebenito commented
> potentially allowing dbus-broker to transition to `initrc_t`

You can run any daemon from `initrc_t` and do other transitions to privileged domains like `fsadm_t`. Now that I think about it, this is effectively arbitrary command execution with the privilege of init, so let's keep the tunables.

I'd prefer `systemd_transient_unit_t`.

2022-03-18 20:36 UTC, pebenito approved these changes

2022-03-18 20:36 UTC, merged