Some more various fixes
SELinuxProject/refpolicy pull request #566
Opened 2022-12-07 18:23 UTC by 0xC0ncord

More minor fixes. Of particular note:
- Add missing rules for `hddtemp` to be used as an interactive application by `sysadm`
- Minor fixes for `netutils` to allow `nmap` and `traceroute` to work
- Minor fixes for `container` to allow [MetalLB's](https://metallb.org/) BGP speakers to run
- Allow `systemd-creds` to `setattr` on directories on RAM filesystems (or else many services fail to start on systemd 252)
- Allow domains sending syslog messages to connect to kernel unix stream sockets. This seems to be because of `journald` starting at boot before the policy is loaded. AVCs around this access seem to be way more prominent on systemd 252.
- Add a filecon for SASL keytab files and allow `postfix_smtpd_t` to read them.
- Various fixes for `libvirtd` and `systemd-machines`.

2022-12-08 13:48 UTC, pebenito requested changes

2022-12-08 13:48 UTC, pebenito commented on policy/modules/services/postfix.te
> +allow postfix_master_t postfix_data_t:file map;
nit: Please merge lines. Making a `mmap_manage_file_perms` would be good too.

2022-12-08 13:48 UTC, pebenito commented on policy/modules/system/init.te
> +		virt_stream_connect(init_t)
This is related to machined?

2022-12-08 14:52 UTC, pebenito commented on policy/modules/system/init.te
> +		virt_stream_connect(init_t)
From what I can tell, it's related to `virtlogd-admin.socket`, so virtlogd needs a socket activation call instead.

2022-12-12 15:29 UTC, pebenito commented
Looks like the `mmap_manage_file_perms` can be used elsewhere:
```
aptcacher.te:        54: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
matrixd.te:          54: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
nsd.te:              47: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
postfix.te:         511: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
mailman.te:         112: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { map manage_file_perms }, would add (none)) (S-010)
mailman.te:         126: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { map manage_file_perms }, would add (none)) (S-010)
mailman.te:         286: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { map manage_file_perms }, would add (none)) (S-010)
mailman.te:         296: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { map manage_file_perms }, would add (none)) (S-010)
mozilla.te:          89: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
pulseaudio.te:       61: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
alsa.te:             71: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
pulseaudio.if:       48: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
apt.if:             194: (S): Suggesting permission macro: mmap_manage_file_perms (replacing { manage_file_perms map }, would add (none)) (S-010)
```

2022-12-12 15:40 UTC, 0xC0ncord commented
Added another commit to replace those instances with the new perm set. :)

2022-12-12 15:47 UTC, pebenito commented
Thanks for the extra change

2022-12-12 15:47 UTC, pebenito approved these changes

2022-12-12 15:47 UTC, merged