rsyslog: add label for /var/empty/dev/log
SELinuxProject/refpolicy pull request #573
Opened 2022-12-16 07:23 UTC by montjoie

On gentoo, starting rsyslog give this:
allow syslogd_t var_t:dir { add_name remove_name }; allow syslogd_t var_t:sock_file { create setattr unlink };

This is due to the following piece of code in configuration: """
 Create an additional socket for the default chroot location
 (used by net-misc/openssh[hpn], see https://bugs.gentoo.org/490744)
 input(type="imuxsock" Socket="/var/empty/dev/log")
"""

So let's add correct label for this file

Signed-off-by: Corentin LABBE <clabbe.montjoie@gmail.com>

2023-01-03 18:55 UTC, pebenito commented
This doesn't seem complete. This will fix the label of the socket on relabel, but what creates `/var/empty/dev`? Perhaps it should be `device_t` and then the socket will be labeled naturally when it is created.

2023-01-03 19:02 UTC, pebenito requested changes
This doesn't seem complete. This will fix the label of the socket on relabel, but what creates `/var/empty/dev`? Perhaps it should be `device_t` and then the socket will be labeled naturally when it is created.

2023-01-04 14:23 UTC, montjoie commented
Ok I do the same than /var/named/chroot/dev

2023-01-05 13:43 UTC, pebenito approved these changes

2023-01-05 13:43 UTC, merged