portage: add misc mising rules
SELinuxProject/refpolicy pull request #579
Opened 2023-01-04 14:11 UTC by montjoie

Add missing rules for portage I encountered while emerging or just calling gcc-config

Signed-off-by: Corentin LABBE <clabbe.montjoie@gmail.com>

2023-01-04 15:56 UTC, pebenito requested changes
cc  @0xC0ncord

2023-01-05 13:42 UTC, pebenito commented
I'm ok with this. @0xC0ncord do you have any comments on this?

2023-01-05 16:29 UTC, 0xC0ncord commented
I don't see anything particularly wrong with these changes although I'm very curious what AVCs were thrown as I'm not able to reproduce these. I'd like to get @perfinion's thougts on this since he is much more knowledgeable on Gentoo-specific policy than I am.

2023-01-06 16:01 UTC, montjoie commented
I checked with my fresh selinux qemu, and hit all thoses AVC also.

2023-01-09 10:04 UTC, montjoie commented
I got some extra AVC when emerging gcc, I work on reproducing and will perhaps update this PR

2023-01-30 00:09 UTC, perfinion approved these changes
These changes look good to me. fairly innocuous overall
Thanks!

2023-02-02 14:05 UTC, pebenito commented
Please click the "Ready for review" button once you are done updating.

2023-03-10 17:28 UTC, 0xC0ncord commented
Just a friendly ping on this one @pebenito. Not sure if Github notifies when a PR is marked as ready, as I just noticed it myself. ;)

2023-03-10 19:58 UTC, pebenito approved these changes

2023-03-10 19:58 UTC, merged