fsadm: add domain for update-smart-drivedb
SELinuxProject/refpolicy pull request #592
Opened 2023-01-27 14:07 UTC by montjoie

update-smart-drivedb is a fsadm_t like but with access to network, so Since it do network access, and dont access any hardware, let's add its own domain.

Signed-off-by: Corentin LABBE <clabbe.montjoie@gmail.com>

2023-01-30 00:13 UTC, perfinion commented on policy/modules/system/fstools.te
>  ifdef(`distro_gentoo',`
Up to @pebenito if this should be in the gentoo-specific block. I don't imagine this would be much different on other distros?

2023-02-02 14:01 UTC, pebenito requested changes

2023-02-02 14:01 UTC, pebenito commented on policy/modules/system/fstools.te
> +allow fsadm_update_drivedb_t self:fifo_file { getattr read write ioctl };
`rw_fifo_file_perms` instead of individual perms.

2023-02-02 14:01 UTC, pebenito commented on policy/modules/system/fstools.te
> +gpg_exec(fsadm_update_drivedb_t)
This should be optional.

2023-02-02 14:01 UTC, pebenito commented on policy/modules/system/fstools.te
> +xdg_read_config_files(fsadm_update_drivedb_t)
Optional.

2023-02-02 17:50 UTC, montjoie commented on policy/modules/system/fstools.te
> +type fsadm_update_drivedb_t;
do you have a name for the new module ? I dont have good idea, smartmon_update ?

2023-02-02 18:58 UTC, 0xC0ncord commented on policy/modules/system/fstools.te
> +type fsadm_update_drivedb_t;
I'm not sure I agree this should be split out into its own module. I think it should just be moved into `smartmon` instead.

2023-02-03 14:54 UTC, 0xC0ncord commented on policy/modules/system/fstools.te
> +type fsadm_update_drivedb_t;
> I'm not sure I agree this should be split out into its own module. I think it should just be moved into `smartmon` instead.

And also just rename it to something like `smartmon_update_drivedb_t`.

2023-02-03 21:14 UTC, pebenito commented on policy/modules/system/fstools.te
> +type fsadm_update_drivedb_t;
> I'm not sure I agree this should be split out into its own module. I think it should just be moved into `smartmon` instead.

Yes, that makes more sense.

2023-03-08 19:24 UTC, pebenito commented
@montjoie there are many unrelated commits here. Please remove them.

2023-03-10 14:40 UTC, pebenito requested changes

2023-03-10 14:40 UTC, pebenito commented on policy/modules/services/smartmon.te
> +init_system_domain(smartmon_update_drivedb_t, smartmon_update_drivedb_exec_t)
This should move down to line 39 to keep the declarations in order..

2023-03-10 14:40 UTC, pebenito commented on policy/modules/services/smartmon.te
> +')
This should go above the `mta_send_mail()` block.

2023-03-10 14:40 UTC, pebenito commented on policy/modules/system/fstools.if
> +')
Move to line 120

2023-03-10 14:40 UTC, pebenito commented on policy/modules/system/fstools.if
> +	allow $1 fsadm_db_t:dir watch;
Please move to a new interface.

2023-04-17 14:23 UTC, pebenito approved these changes

2023-04-17 14:23 UTC, merged