dovecot: add missing permissions
SELinuxProject/refpolicy pull request #608
Opened 2023-03-22 10:54 UTC by montjoie

I use dovecot for IMAP hosting and several rules are missing.

2023-03-31 15:17 UTC, 0xC0ncord commented on policy/modules/services/dovecot.te
> +allow dovecot_t dovecot_spool_t:file map;
This can be combined with the below `manage_files_pattern()` to `mmap_manage_files_pattern()`.

2023-04-04 19:02 UTC, pebenito requested changes

2023-04-04 19:02 UTC, pebenito commented on policy/modules/services/dovecot.te
> +allow dovecot_deliver_t self:process signal;
This should be the first line of the block, line 341

2023-04-17 14:17 UTC, pebenito approved these changes

2023-04-17 14:17 UTC, merged