container: set default context for local-path-provisioner
SELinuxProject/refpolicy pull request #612
Opened 2023-04-18 15:12 UTC by jcpunk

The kubernetes local-path-provisioner uses either
/opt/local-path-provisioner or
/var/local-path-provisioner for its physical volumes

2023-04-20 19:09 UTC, jcpunk commented
Moving this to the container specific selinux policy https://github.com/containers/container-selinux/pull/228

2023-04-25 20:56 UTC, 0xC0ncord commented
container-selinux is an add-on policy for Fedora and derivatives (RHEL, Rocky, etc.) specifically while refpolicy aims to have wider compatibility. Your PR is still relevant here if you're willing to reopen this.

That being said, the only thing I would change is to split the `(var|opt)` regex into separate lines so that it is more consistent with the refpolicy code style.

2023-04-26 13:25 UTC, jcpunk commented
I've reopened this PR and in theory made the changes you suggested.

2023-04-28 20:13 UTC, pebenito requested changes

2023-04-28 20:13 UTC, pebenito commented on policy/modules/services/container.fc
> +/opt/local-path-provisioner(/.*)?		gen_context(system_u:object_r:container_file_t,s0)
Please move up to line 34.

2023-04-28 20:16 UTC, jcpunk commented on policy/modules/services/container.fc
> +/opt/local-path-provisioner(/.*)?		gen_context(system_u:object_r:container_file_t,s0)
Does that look better?

2023-04-28 20:18 UTC, pebenito commented on policy/modules/services/container.fc
> +/opt/local-path-provisioner(/.*)?		gen_context(system_u:object_r:container_file_t,s0)
Yes, thanks

2023-04-28 20:47 UTC, merged