Add interfaces for systemd-hostnamed units
SELinuxProject/refpolicy pull request #633
Opened 2023-08-16 15:50 UTC by dsugar100

node=localhost type=USER_AVC msg=audit(1689811749.504:399): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=81 path="/usr/lib/systemd/system/systemd-hostnamed.service" cmdline="/usr/bin/dbus-broker-launch --scope system --audit" function="bus_unit_method_start_generic" scontext=system_u:system_r:system_dbusd_t:s0 tcontext=system_u:object_r:systemd_unit_t:s0 tclass=service permissive=0 exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=?  terminal=?' UID="root" AUID="unset" AUID="root" UID="root" GID="dbus" SAUID="root"

2023-08-18 15:55 UTC, pebenito requested changes
Minor doc issue.

2023-08-18 15:55 UTC, pebenito commented on policy/modules/system/systemd.if
> +##	Allow specified domain to start systemd-hostnamed units
Missing stop.

2023-09-02 00:44 UTC, dsugar100 commented
I'm kind of also wondering if it would be preferable to just allow dbusd_t to start/stop all systemd units?  Thoughts?

2023-09-05 14:40 UTC, pebenito commented
> I'm kind of also wondering if it would be preferable to just allow system_dbusd_t to start/stop all systemd units? Thoughts?

Possibly. Potentially any unit could be dbus activated.

2023-09-06 15:38 UTC, dsugar100 commented
Replaced by merge request #655

2023-09-06 15:38 UTC, closed without merging