Policy for firmware update daemon
SELinuxProject/refpolicy pull request #664
Opened 2023-09-08 13:47 UTC by etbe

2023-09-11 13:30 UTC, pebenito requested changes

2023-09-11 13:30 UTC, pebenito commented on policy/modules/system/fwupd.te
> +allow fwupd_t self:netlink_kobject_uevent_socket { create getattr setopt bind read };
Please use `create_socket_perms`.

2023-09-11 13:30 UTC, pebenito commented on policy/modules/system/fwupd.te
> +init_daemon_domain(fwupd_t, fwupd_exec_t)
Why does the command line tool run in this domain if it is a daemon? Which part (daemon/cli) does the firmware install?

2023-09-14 13:13 UTC, etbe commented on policy/modules/system/fwupd.te
> +allow fwupd_t self:netlink_kobject_uevent_socket { create getattr setopt bind read };
ok

2023-11-21 02:09 UTC, closed without merging